Quad_footstep_planner:
  Grid_map_topic : /elevation_mapping/elevation_map_raw
  Grid_map_resolution : 0.05
  visualize_plan : true
  max_steplength : 0.13
  min_steplength : 0.09
  favoured_steplength : 0.09
  resolution_steplength : 0.01
  prefered_stepcostFactor : 0.7
  obstacle_stepcostFactor : 0.6
  collision_costFactor : 1.2
  global_costFactor : 0.4
  edge_costFactor : 1000.0
  using_joystick : true
  joystick_topic : /joy
  horizon_length : 3
  foot_plan_horizon : 5
  vx_samples : 5
  vtheta_samples : 10
  global_goal_topic : /aliengo_goal