Quad_footstep_planner:
  Grid_map_topic : /elevation_mapping/elevation_map_raw
  Grid_map_resolution : 0.05
  visualize_plan : true
  max_steplength : 0.35
  min_steplength : 0.17
  favoured_steplength : 0.17
  resolution_steplength : 0.03
  prefered_stepcostFactor : 3.5
  obstacle_stepcostFactor : 0.01
  collision_costFactor : 5.2
  global_costFactor : 0.4
  edge_costFactor : 3000
  using_joystick : true
  joystick_topic : /joy
  horizon_length : 4
  foot_plan_horizon : 5
  vx_samples : 6
  vtheta_samples : 4
  global_goal_topic : /aliengo_goal