global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 0.5
  publish_frequency: 0.5
  static_map: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[0.44, -0.21], [-0.44, -0.21], [-0.44, 0.21], [0.44, 0.21]]
  inflation_radius: 0.6
  transform_tolerance: 1
  controller_patience: 2.0

  NavfnROS:
    allow_unknown: true

  plugins:
   - {name: static_layer, type: "rtabmap_costmap_plugins::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}