global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 5.0
  static_map: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[0.34, -0.11], [-0.34, -0.11], [-0.34, 0.11], [0.34, 0.11]]
  inflation_radius: 0.13


NavfnROS:
   allow_unknown: true