robot_config:
  base_length: 0.4798
  base_width: 0.102
  L1:  0.083
  L2: 0.25
  L3: 0.25
  collision_rect_length: 0.65
  collision_rect_width: 0.3
  collision_point_height: 0.2
  collision_threshold: 20.5
  collision_free_threshold: 99.5
  max_forward_vel:  0.5
  min_angular_vel: -0.7
  max_angular_vel: 0.7
  robot_base_frame: base
  foot_radius: 0.0265