robot_config:
  base_length: 0.4798
  base_width: 0.102
  L1:  0.083
  L2: 0.25
  L3: 0.25
  collision_rect_length: 0.65
  collision_rect_width: 0.3
  collision_point_height: 0.2
  collision_threshold: 0.01
  collision_free_threshold: 99.5
  max_forward_vel:  0.18
  min_angular_vel: -0.1
  max_angular_vel: 0.1
  robot_base_frame: base
  foot_radius: 0.0265
  robot_name: aliengo

Quad_controller:
    robot_verti_vel: 0.3
    robot_base_height: 0.35
    robot_swing_height: 0.05
    controller_rate: 2000
    walk_swing_time: 0.6
    walk_base_time: 0.4
    offset_velocity: 0.02
    minimum_steplength: 0.02
    favoured_steplength: 0.05